def generate_business_summary(
    health_score,
    best_category,
    worst_category,
    best_region,
    worst_region
):

    summary = []

    # Health

    if health_score >= 80:

        summary.append(
            "Business health is excellent."
        )

    elif health_score >= 60:

        summary.append(
            "Business health is healthy with opportunities for improvement."
        )

    else:

        summary.append(
            "Business performance requires immediate attention."
        )

    # Category Insights

    summary.append(
        f"Highest profit is generated by {best_category}."
    )

    summary.append(
        f"{worst_category} is the weakest category."
    )

    # Region Insights

    summary.append(
        f"{best_region} region contributes the highest profit."
    )

    summary.append(
        f"{worst_region} region is underperforming."
    )

    return summary